import type { Banner, Category, Product, Testimonial } from "@/types/product";

export const fallbackCategories: Category[] = [
  { id: "1", name: "RO Water Purifiers", slug: "ro-water-purifiers", productCount: 0, image: "/images/fallback/categories/ro-water-purifiers.webp" },
  { id: "2", name: "Alkaline Water Purifiers", slug: "alkaline-water-purifiers", productCount: 0, image: "/images/fallback/categories/alkaline-water-purifiers.webp" },
  { id: "3", name: "Electronics", slug: "electronics", productCount: 0, image: "/images/fallback/categories/electronics.webp" },
  { id: "4", name: "Commercial Water Purifiers", slug: "commercial-water-purifiers", productCount: 0, image: "/images/fallback/categories/commercial-water-purifiers.webp" },
  { id: "5", name: "Spare Parts", slug: "spare-parts", productCount: 0, image: "/images/fallback/categories/spare-parts.webp" },
];

export const fallbackBanners: Banner[] = [
  {
    id: "1",
    title: "Alkaline Water Purifiers",
    subtitle: "Advanced alkaline purification for healthier everyday water",
    description: "Experience clean, fresh and balanced alkaline water with Priya's Aqua Fresh. Designed for modern homes, this purifier delivers safer drinking water, better taste and dependable daily performance.",
    image: "/images/fallback/banners/alkaline-water-purifiers.webp",
    buttonText: "Explore Alkaline Range",
    buttonLink: "/products?category=alkaline-water-purifiers",
    themeColor: "#2dd4bf",
    glowColor: "rgba(45, 212, 191, 0.34)",
    sortOrder: 1,
  },
  {
    id: "4",
    title: "RO Water Purifiers",
    subtitle: "Advanced RO purification for safer drinking water",
    description: "Get dependable RO water purifiers built to reduce impurities, improve taste and deliver clean drinking water for families, offices and everyday use.",
    image: "/images/fallback/banners/ro-water-purifiers.webp",
    buttonText: "Explore RO Purifiers",
    buttonLink: "/products?category=ro-water-purifiers",
    themeColor: "#38bdf8",
    glowColor: "rgba(56, 189, 248, 0.34)",
    sortOrder: 2,
  },
  {
    id: "2",
    title: "Commercial Water Purifiers",
    subtitle: "High-capacity purification for business and commercial spaces",
    description: "Powerful commercial RO water purification systems designed for offices, hotels, schools, hospitals, restaurants and large facilities that need reliable clean water every day.",
    image: "/images/fallback/banners/commercial-water-purifiers.webp",
    buttonText: "Explore Commercial RO",
    buttonLink: "/commercial",
    themeColor: "#4ade80",
    glowColor: "rgba(74, 222, 128, 0.30)",
    sortOrder: 3,
  },
  {
    id: "3",
    title: "Electronics",
    subtitle: "Smart electronics for modern homes",
    description: "Explore reliable home electronics and smart TV solutions selected for everyday entertainment, clear visuals, smooth performance and long-lasting value.",
    image: "/images/fallback/banners/electronics.webp",
    buttonText: "Explore Range",
    buttonLink: "/products?category=electronics",
    themeColor: "#818cf8",
    glowColor: "rgba(45, 212, 191, 0.34)",
    sortOrder: 4,
  },
];

export const fallbackProducts: Product[] = [
  {
    id: "1",
    slug: "priyas-aquafresh-stell-guard-alkaline",
    sku: "PRIYASAQUAFRESHSTE-MSLT2DML",
    name: "PRIYAS AQUAFRESH STELL GUARD ALKALINE",
    category: "Alkaline Water Purifiers",
    description: "PRIYAS AQUAFRESH ERA Alkaline Water Purifier is designed for modern homes, offices, and small commercial spaces.",
    price: 25000,
    originalPrice: 27000,
    customerPrice: 25000,
    customerOriginalPrice: 27000,
    dealerPrice: 23980,
    dealerOriginalPrice: 26000,
    discount: 7,
    rating: 3,
    reviewCount: 5,
    image: "/images/fallback/products/priyas-aquafresh-stell-guard-alkaline.webp",
    images: ["/images/fallback/products/priyas-aquafresh-stell-guard-alkaline.webp"],
    stock: "in-stock",
  },
  {
    id: "2",
    slug: "priyas-aquafresh-alkaline-pro",
    sku: "PYA-ALK-001",
    name: "Priyas AquaFresh Alkaline Pro",
    category: "Alkaline Water Purifiers",
    description: "Advanced alkaline purifier designed for fresh-tasting water, balanced minerals, and reliable daily use.",
    price: 21999,
    originalPrice: 24999,
    customerPrice: 21999,
    customerOriginalPrice: 24999,
    dealerPrice: 19999,
    dealerOriginalPrice: 22999,
    discount: 12,
    rating: 4.8,
    reviewCount: 42,
    image: "/images/fallback/products/priyas-aquafresh-alkaline-pro.webp",
    images: ["/images/fallback/products/priyas-aquafresh-alkaline-pro.webp"],
    stock: "in-stock",
  },
  {
    id: "3",
    slug: "priyas-aquafresh-ro-classic",
    sku: "PYA-RO-001",
    name: "Priyas AquaFresh RO Classic",
    category: "RO Water Purifiers",
    description: "Compact RO water purifier for homes, built for dependable filtration and clean drinking water.",
    price: 16999,
    originalPrice: 19999,
    customerPrice: 16999,
    customerOriginalPrice: 19999,
    dealerPrice: 15499,
    dealerOriginalPrice: 18499,
    discount: 15,
    rating: 4.7,
    reviewCount: 36,
    image: "/images/fallback/products/priyas-aquafresh-ro-classic.webp",
    images: ["/images/fallback/products/priyas-aquafresh-ro-classic.webp"],
    stock: "in-stock",
  },
  {
    id: "4",
    slug: "priyas-commercial-ro-100-lph",
    sku: "PYA-COM-100",
    name: "Priyas Commercial RO 100 LPH",
    category: "Commercial Water Purifiers",
    description: "Commercial RO purification system for offices, hotels, schools, hospitals, and high-usage facilities.",
    price: 78999,
    originalPrice: 85000,
    customerPrice: 78999,
    customerOriginalPrice: 85000,
    dealerPrice: 73500,
    dealerOriginalPrice: 79999,
    discount: 7,
    rating: 4.9,
    reviewCount: 28,
    image: "/images/fallback/products/priyas-commercial-ro-100-lph.webp",
    images: ["/images/fallback/products/priyas-commercial-ro-100-lph.webp"],
    stock: "in-stock",
  },
  {
    id: "5",
    slug: "priyas-smart-led-tv-32-inch",
    sku: "PYA-TV-032",
    name: "Priyas Smart LED TV 32 Inch",
    category: "Electronics",
    description: "Smart LED TV with vivid display quality and practical connectivity for everyday home entertainment.",
    price: 14999,
    originalPrice: 17999,
    customerPrice: 14999,
    customerOriginalPrice: 17999,
    dealerPrice: 13499,
    dealerOriginalPrice: 16499,
    discount: 17,
    rating: 4.6,
    reviewCount: 31,
    image: "/images/fallback/products/priyas-smart-led-tv-32-inch.webp",
    images: ["/images/fallback/products/priyas-smart-led-tv-32-inch.webp"],
    stock: "in-stock",
  },
  {
    id: "6",
    slug: "priyas-ro-service-filter-kit",
    sku: "PYA-SPARE-001",
    name: "Priyas RO Service Filter Kit",
    category: "Spare Parts",
    description: "Genuine RO filter and spare-part kit for routine purifier service and maintenance.",
    price: 2999,
    originalPrice: 3499,
    customerPrice: 2999,
    customerOriginalPrice: 3499,
    dealerPrice: 2599,
    dealerOriginalPrice: 3199,
    discount: 14,
    rating: 4.7,
    reviewCount: 24,
    image: "/images/fallback/products/priyas-ro-service-filter-kit.webp",
    images: ["/images/fallback/products/priyas-ro-service-filter-kit.webp"],
    stock: "in-stock",
  },
];

export const fallbackTestimonials: Testimonial[] = [
  {
    id: "fallback-customer-1",
    name: "Ramesh Kumar",
    role: "Customer",
    rating: 5,
    review: "The water taste improved from the first day, and the installation team explained everything clearly.",
    product: "RO Water Purifier",
    avatar: "R",
  },
  {
    id: "fallback-customer-2",
    name: "Anitha Rao",
    role: "Customer",
    rating: 5,
    review: "Good product quality and quick support. The purifier looks clean in our kitchen and works well.",
    product: "Alkaline Water Purifier",
    avatar: "A",
  },
  {
    id: "fallback-customer-3",
    name: "Suresh Patel",
    role: "Dealer",
    rating: 4.8,
    review: "Priya's Aqua Fresh products are dependable, and customers ask for repeat service with confidence.",
    product: "Commercial RO",
    avatar: "S",
  },
];

export function getFallbackProductBySlug(slug: string) {
  return fallbackProducts.find((product) => product.slug === slug) || null;
}
